### ISSUE TITLE
Relation to ServerPilot.io?

### ISSUE THREAD

**Issue by leepeterson** [sitepilot/serverpilot#20]
Just curious if the intent behind this stack is to closely mimic or clone the ServerPilot.io stack. I do see some noticeable differences, but I realize it is also a work-in-progress repo.

**Comment by nbejansen** [comment]
@leepeterson 

Thank you for your message! This repo has nothing to do with ServerPilot.io. It's just a CLI for local website development in docker. You can create apps based on a preconfigured (LAMP) stack.

**Comment by nbejansen** [comment]
Renamed to Dockerpilot to prevent confusion 👍
